bpo-30380: Pin the version of Sphinx used to build the documentation (GH-1612)

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -28,7 +28,29 @@ matrix:
         - TESTING=docs
       before_script:
         - cd Doc
-        - pip install -U Sphinx
+        # Sphinx is pinned so that new versions that introduce new warnings won't suddenly cause build failures.
+        # (Updating the version is fine as long as no warnings are raised by doing so.)
+        - python -m pip install sphinx~=1.6.1
+      script:
+        - make check suspicious html SPHINXOPTS="-q -W"
+    - os: linux
+      language: c
+      compiler: gcc
+      env:
+        - TESTING=coverage
+      before_script:
+        - |
+            if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.(rst|yml)$)|(^Doc)|(^Misc)/'
+            then
+              echo "Only docs were updated, stopping build process."
+              exit
+            fi
+            ./configure
+            make -s -j4
+            # Need a venv that can parse covered code.
+            ./python -m venv venv
+            ./venv/bin/python -m pip install -U coverage
+>>>>>>> fca224f117... bpo-30380: Pin the version of Sphinx used to build the documentation (GH-1612)
       script:
         - make check suspicious html SPHINXOPTS="-q -W"
 
