Add iOS testbed, plus Makefile target to invoke it.

diff --git a/Makefile.pre.in b/Makefile.pre.in
--- a/Makefile.pre.in
+++ b/Makefile.pre.in
@@ -1994,6 +1994,21 @@ testuniversal: all
 	$(RUNSHARED) /usr/libexec/oah/translate \
 		./$(BUILDPYTHON) -E -m test -j 0 -u all $(TESTOPTS)
 
+# Run the test suite on the iOS simulator.
+# Must be run on a macOS machine with a full Xcode install that has an iPhone SE
+# (3rd edition) simulator available, after running `make install` on a configuration
+# with --enable-framework="./iOS/testbed/Python.xcframework/ios-arm64_x86_64-simulator"
+XCRESULT=$(srcdir)/build/$(MULTIARCH).$(shell date +%s).xcresult
+.PHONY: testiOS
+testiOS:
+	# Run the test suite for the Xcode project, targeting the iOS simulator.
+	# If the suite fails, extract and print the console output, then re-raise the failure
+	if ! xcodebuild test -project $(srcdir)/iOS/testbed/iOSTestbed.xcodeproj -scheme "iOSTestbed" -destination "platform=iOS Simulator,name=iPhone SE (3rd Generation)" -resultBundlePath $(XCRESULT) ; then \
+		xcrun xcresulttool get --path $(XCRESULT) --id $$(xcrun xcresulttool get --path $(XCRESULT) --format json | $(PYTHON_FOR_BUILD) -c "import sys, json; result = json.load(sys.stdin); print(result['actions']['_values'][0]['actionResult']['logRef']['id']['_value'])"); \
+		echo ; \
+		exit 1; \
+	fi
+
 # Like test, but using --slow-ci which enables all test resources and use
 # longer timeout. Run an optional pybuildbot.identify script to include
 # information about the build environment.
@@ -2713,7 +2728,7 @@ frameworkinstallextras:
 # subdirectory. The install has put these folders in the same folder as
 # Python.framework; Move the headers to their final framework-compatible home.
 .PHONY: frameworkinstallmobileheaders
-frameworkinstallmobileheaders:
+frameworkinstallmobileheaders: frameworkinstallunversionedstructure inclinstall
 	if test -d $(DESTDIR)$(PYTHONFRAMEWORKINSTALLDIR)/Headers; then \
 		echo "Removing old framework headers"; \
 		rm -rf $(DESTDIR)$(PYTHONFRAMEWORKINSTALLDIR)/Headers; \
@@ -2848,6 +2863,14 @@ clean-retain-profile: pycremoval
 	-find build -type f -a ! -name '*.gc??' -exec rm -f {} ';'
 	-rm -f Include/pydtrace_probes.h
 	-rm -f profile-gen-stamp
+	-rm -rf iOS/testbed/Python.xcframework/ios-arm64/bin
+	-rm -rf iOS/testbed/Python.xcframework/ios-arm64/lib
+	-rm -rf iOS/testbed/Python.xcframework/ios-arm64/include
+	-rm -rf iOS/testbed/Python.xcframework/ios-arm64/Python.framework
+	-rm -rf iOS/testbed/Python.xcframework/ios-arm64_x86_64-simulator/bin
+	-rm -rf iOS/testbed/Python.xcframework/ios-arm64_x86_64-simulator/lib
+	-rm -rf iOS/testbed/Python.xcframework/ios-arm64_x86_64-simulator/include
+	-rm -rf iOS/testbed/Python.xcframework/ios-arm64_x86_64-simulator/Python.framework
 
 .PHONY: profile-removal
 profile-removal:
