Move more logic into configure

diff --git a/Makefile.pre.in b/Makefile.pre.in
--- a/Makefile.pre.in
+++ b/Makefile.pre.in
@@ -313,16 +313,15 @@ HOST_GNU_TYPE=	@host@
 # PROFILE_TASK="-m test --pgo-extended"
 PROFILE_TASK=	@PROFILE_TASK@
 
-# report files for gcov / lcov coverage report
-COVERAGE_INFO=	$(abs_builddir)/coverage.info
-COVERAGE_REPORT=$(abs_builddir)/lcov-report
-COVERAGE_LCOV_OPTIONS=--rc lcov_branch_coverage=1
-COVERAGE_REPORT_OPTIONS=--rc lcov_branch_coverage=1 --branch-coverage --title "CPython $(VERSION) LCOV report [commit $(shell $(GITVERSION))]"
-
-# report files for llvm-cov coverage report
-COVERAGE_INFO_LLVM=	$(abs_builddir)/coverage.profdata
-COVERAGE_REPORT_LLVM=$(abs_builddir)/llvm-cov-report
-COVERAGE_REPORT_OPTIONS_LLVM=-show-branches=count -show-regions
+# parameters for coverage
+COVERAGE_CC=@COVERAGE_CC@
+COVERAGE_CFLAGS=@COVERAGE_CFLAGS@
+COVERAGE_LDFLAGS=@COVERAGE_LDFLAGS@
+COVERAGE_GEN_TARGET=@COVERAGE_GEN_TARGET@
+COVERAGE_INFO=$(abs_builddir)/@COVERAGE_INFO@
+COVERAGE_REPORT=$(abs_builddir)/coverage-report
+COVERAGE_OPTIONS=@COVERAGE_OPTIONS@
+COVERAGE_REPORT_OPTIONS=@COVERAGE_REPORT_OPTIONS@
 
 # === Definitions added by makesetup ===
 
@@ -662,36 +661,38 @@ bolt-opt: @PREBOLT_RULE@
 	rm -f $(BUILDPYTHON).bolt_inst
 	mv $(BUILDPYTHON).bolt $(BUILDPYTHON)
 
-.PHONY=coverage-report
+.PHONY=coverage-report coverage coverage-generate-lcov coverage-generate-profdata
 coverage-report:
-	@if [ $(CC_NAME) = "gcc" ]; then \
-		$(MAKE) coverage-report-lcov; \
-	elif [ $(CC_NAME) = "clang" ]; then \
-		$(MAKE) coverage-report-llvm; \
-	else \
-		echo "Coverage is not supported with the $(CC_NAME) compiler"; \
-		exit 1; \
-	fi
+	@ # build with coverage info
+	$(MAKE) coverage
+	@ # run tests, ignore failures
+	@ # The LLVM_PROFILE_FILE must specify %m so results can be collected in parallel.
+	@ # Also, must be an absolute path since test suite changes working directory.
+	LLVM_PROFILE_FILE=${abs_builddir}/python%m.profraw $(TESTRUNNER) $(TESTOPTS) || true
+	@ # build lcov report
+	$(MAKE) $(COVERAGE_GEN_TARGET)
+	@echo
+	@echo "coverage report at $(COVERAGE_REPORT)/index.html"
+	@echo
 
-# Compile and run with gcov
-.PHONY=coverage-gcc coverage-lcov coverage-report-lcov
-coverage-gcc:
+# Compile and run generating coverage
+coverage:
 	@echo "Building with support for coverage checking:"
 	$(MAKE) clean
-	$(MAKE) @DEF_MAKE_RULE@ CFLAGS="$(CFLAGS) -O0 -pg --coverage" LDFLAGS="$(LDFLAGS) --coverage"
+	$(MAKE) @DEF_MAKE_RULE@ CC="$(COVERAGE_CC)" CFLAGS="$(CFLAGS) $(COVERAGE_CFLAGS)" LDFLAGS="$(LDFLAGS) $(COVERAGE_LDFLAGS)"
 
-coverage-lcov:
+coverage-generate-lcov:
 	@echo "Creating Coverage HTML report with LCOV:"
 	@rm -f $(COVERAGE_INFO)
 	@rm -rf $(COVERAGE_REPORT)
-	@lcov $(COVERAGE_LCOV_OPTIONS) --capture \
+	@lcov $(COVERAGE_OPTIONS) --capture \
 	    --directory $(abs_builddir) \
 	    --base-directory $(realpath $(abs_builddir)) \
 	    --path $(realpath $(abs_srcdir)) \
 	    --output-file $(COVERAGE_INFO)
 	@ # remove 3rd party modules, system headers and internal files with
 	@ # debug, test or dummy functions.
-	@lcov $(COVERAGE_LCOV_OPTIONS) --remove $(COVERAGE_INFO) \
+	@lcov $(COVERAGE_OPTIONS) --remove $(COVERAGE_INFO) \
 	    '*/Modules/_blake2/impl/*' \
 	    '*/Modules/_ctypes/libffi*/*' \
 	    '*/Modules/_decimal/libmpdec/*' \
@@ -706,51 +707,15 @@ coverage-lcov:
 	@genhtml $(COVERAGE_INFO) \
 	    --output-directory $(COVERAGE_REPORT) \
 	    $(COVERAGE_REPORT_OPTIONS)
-	@echo
-	@echo "lcov report at $(COVERAGE_REPORT)/index.html"
-	@echo
 
-# Force regeneration of parser and frozen modules
-coverage-report-lcov: regen-token regen-frozen
-	@ # build with coverage info
-	$(MAKE) coverage-gcc
-	@ # run tests, ignore failures
-	$(TESTRUNNER) $(TESTOPTS) || true
-	@ # build lcov report
-	$(MAKE) coverage-lcov
-
-# Compile and calculate coverage with llvm-cov
-.PHONY=coverage-clang coverage-profdata coverage-report-llvm
-
-coverage-clang: 
-	@echo "Building with support for coverage checking:"
-	$(MAKE) clean
-	@ # Override CC rather than CFLAGS since these flags must come first
-	$(MAKE) @DEF_MAKE_RULE@ CC="$(CC) -fprofile-instr-generate -fcoverage-mapping"
-
-coverage-profdata:
+coverage-generate-profdata:
 	@echo "Creating Coverage HTML report with llvm-profdata/llvm-cov:"
-	@rm -f $(COVERAGE_INFO_LLVM)
-	@rm -rf $(COVERAGE_REPORT_LLVM)
+	@rm -f $(COVERAGE_INFO)
+	@rm -rf $(COVERAGE_REPORT)
 	@ # Merge coverage results
-	$(LLVM_PROFDATA) merge -sparse python*.profraw -o $(COVERAGE_INFO_LLVM)
+	$(LLVM_PROFDATA) merge -sparse python*.profraw -o $(COVERAGE_INFO)
 	@ # Generate HTML
-	$(LLVM_COV) show -format=html -output-dir=$(COVERAGE_REPORT_LLVM) -instr-profile=$(COVERAGE_INFO_LLVM) $(COVERAGE_REPORT_OPTIONS_LLVM) python .
-	@echo
-	@echo "llvm-cov report at $(COVERAGE_REPORT_LLVM)/index.html"
-	@echo
-
-# Force regeneration of parser and importlib
-# Specify the LLVM_PROFILE_FILE using %m so multiple shared objects can write
-# in parallel. Set the full path to the directory so results aren't written
-# into temporary directories created by tests.
-coverage-report-llvm: regen-token regen-importlib
-	@ # build with coverage info
-	$(MAKE) coverage-clang
-	@ # run tests, ignore failures
-	LLVM_PROFILE_FILE=${PWD}/python%m.profraw $(TESTRUNNER) $(TESTOPTS) || true
-	@ # build llvm-cov report
-	$(MAKE) coverage-profdata
+	$(LLVM_COV) show -format=html -output-dir=$(COVERAGE_REPORT) -instr-profile=$(COVERAGE_INFO) $(COVERAGE_REPORT_OPTIONS) python .
 
 # Run "Argument Clinic" over all source files
 .PHONY=clinic
