Ensure Doc build has Misc/NEWS for changelog

diff --git a/Doc/Makefile b/Doc/Makefile
--- a/Doc/Makefile
+++ b/Doc/Makefile
@@ -5,6 +5,7 @@
 
 # You can set these variables from the command line.
 PYTHON       = python
+BLURB        = blurb
 SVNROOT      = http://svn.python.org/projects
 SPHINXOPTS   =
 PAPER        =
@@ -60,6 +61,19 @@ update: clean checkout
 
 build: checkout
 	mkdir -p build/$(BUILDER) build/doctrees
+# Look first for a Misc/NEWS file (building from a source release tarball
+# or old repo) and use that, otherwise look for a Misc/NEWS.d directory
+# (building from a newer repo) and use blurb to generate the NEWS file.
+	@if [ -f  ../Misc/NEWS ] ; then \
+		echo "Using existing Misc/NEWS file"; \
+		cp ../Misc/NEWS build/NEWS; \
+	elif [ -d ../Misc/NEWS.d ]; then \
+		echo "Building NEWS from Misc/NEWS.d with blurb"; \
+		$(BLURB) merge -f build/NEWS; \
+	else \
+		echo "Neither Misc/NEWS.d nor Misc/NEWS found; cannot build docs"; \
+		exit 1; \
+	fi
 	$(PYTHON) tools/sphinx-build.py $(ALLSPHINXOPTS)
 	@echo
 
